export const Labs = [
    {text: 'CD4 + cell count'},
        {text: 'CD4 + cell count'},
            {text: 'CD4%'},
    {text: 'CD4 LFA'},
    {text: 'WBC'},
    {text: 'Polymorphs'},
    {text: 'Lymphocytes'},
    {text: 'Monocytes'},
    {text: 'Eosinophils'},
    {text: 'Basophils'},
    {text: 'PCV/Hb'},
    {text: 'Platelets'},
    {text: 'HCV Antibody'},
    {text: 'HBsAG'},
    {text: 'VDRL'},
    {text: 'Creatinine'},
    {text: 'ALT/SGPT'},

    {text: 'Alk. Phosphatase'},
    {text: 'Total Bilirubin'},
    {text: 'Na+'},
    {text: 'K+'},
    {text: 'Fasting Glucose'},
    {text: 'Total Cholesterol'},
    {text: 'LDL'},
    {text: 'HDL'},
    {text: 'Triglycerides'},
    {text: 'Urinalysis'},
    {text: 'Cytology: VIA/Pap smear'},
    {text: 'TB LF LAM'},
    {text: 'Pregnancy'},
    {text: 'Malaria smear'},
    {text: 'Serology for Cr Ag'},
    {text: 'CSF for Cr Ag'},
    {text: 'CSF M/C/S'},
]